repos:
  - repo: local
    hooks:
      - id: validate-readme
        name: Validate README structure
        entry: python .github/scripts/validate_readme.py
        language: python
        files: '.*README\.md$'
        pass_filenames: false
        always_run: true