[project]
name = "brand-reputation-monitoring-workflow"
version = "0.1.0"
description = "AI-powered brand reputation monitoring workflow using Bright Data SDK, OpenAI, and SendGrid SDK"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "python-dotenv>=1.1.1",
    "brightdata-sdk>=1.0.7",
    "openai>=1.101.0",
    "sendgrid>=6.12.4",
    "pydantic>=2.11.7"
]
